version: '3.8'

services:
  arangodb:
    image: arangodb:3.10
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: hilton
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data:
